version: 2.1
jobs:
  code_analysis:
    docker:
      - image: circleci/python:3.9.6
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Code Analysis
          command: pylint data_tools/
  run_tests:
    docker:
      - image: circleci/python:3.9.6
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Unit Tests
          command: pytest --no-header -v tests/unit/*
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  build_test:
    jobs:
      - code_analysis
      - run_tests